"""Unit tests for ConfigManager, Configuration Schema, and Composition Root (PRD §13 / §14)."""

import os
import unittest
import tempfile
import yaml
from pathlib import Path

from macao.core.config import ConfigManager, DEFAULT_CONFIG_FILENAME
from macao.core.schema import validate_config
from macao.cli.main import DEFAULT_CONFIG_TEMPLATE
from macao.adapter.mock import MockAgentAdapter
from macao.adapter.claude import ClaudeCodeAdapter
from macao.adapter.codex import CodexAdapter
from macao.adapter.kimi import KimiAdapter
from macao.workflow.orchestrator import Orchestrator


class TestConfigAndComposition(unittest.TestCase):

    def test_default_config_template_validates_against_schema(self):
        """Verify that the template generated by macao init strictly complies with schema."""
        parsed = yaml.safe_load(DEFAULT_CONFIG_TEMPLATE)
        is_valid, error = validate_config(parsed)
        self.assertTrue(is_valid, f"Template failed schema validation: {error}")

    def test_config_manager_property_accessors(self):
        """Verify that ConfigManager reads the actual schema-defined paths."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "macao.yaml")
            with open(cfg_path, "w", encoding="utf-8") as f:
                f.write(DEFAULT_CONFIG_TEMPLATE)

            mgr = ConfigManager(cfg_path)
            mgr.load()

            self.assertEqual(mgr.project_name, "macao-demo")
            self.assertEqual(mgr.target_branch, "main")
            self.assertEqual(mgr.remote_name, "origin")
            self.assertEqual(mgr.min_effective_votes, 2)
            self.assertEqual(mgr.max_rework_rounds, 3)
            self.assertTrue(mgr.require_human_signoff)
            self.assertTrue(mgr.auto_rebase_disabled)
            self.assertIsNone(mgr.ci_gate_command)
            self.assertEqual(len(mgr.reviewers_config), 2)

    def test_orchestrator_config_injection(self):
        """Verify Orchestrator receives injected configuration rather than hardcoded fallbacks."""
        custom_config = {
            "max_rework_rounds": 5,
            "min_effective_votes": 3,
            "ci_gate_command": "pytest -q",
            "require_signoff": True
        }
        orch = Orchestrator(project_root=".", config=custom_config)
        self.assertEqual(orch.config["max_rework_rounds"], 5)
        self.assertEqual(orch.config["min_effective_votes"], 3)
        self.assertEqual(orch.config["ci_gate_command"], "pytest -q")
        self.assertTrue(orch.config["require_signoff"])

    def test_adapter_preflight_probes_no_type_error(self):
        """Verify all adapter preflight probes return valid PreflightCheckResult objects."""
        adapters = [
            MockAgentAdapter("mock-1", "mock-cli"),
            ClaudeCodeAdapter(),
            CodexAdapter(),
            KimiAdapter()
        ]
        for adp in adapters:
            res = adp.preflight()
            self.assertIsNotNone(res)
            self.assertIn(adp.cli_name, (res.cli_name, res.agent_id))
            self.assertIsInstance(res.installed, bool)


if __name__ == "__main__":
    unittest.main()
