"""Unit tests for ConfigManager, Configuration Schema, and Composition Root (PRD §13 / §14)."""

import os
import unittest
import tempfile
import yaml
from pathlib import Path

from macao.core.config import ConfigManager, DEFAULT_CONFIG_FILENAME
from macao.core.schema import validate_config
from macao.cli.main import DEFAULT_CONFIG_TEMPLATE
from macao.adapter.mock import MockAgentAdapter
from macao.adapter.claude import ClaudeCodeAdapter
from macao.adapter.codex import CodexAdapter
from macao.adapter.opencode import OpenCodeAdapter
from macao.adapter.antigravity import AntigravityAdapter
from macao.adapter.kimi import KimiAdapter
from macao.workflow.orchestrator import Orchestrator


class TestConfigAndComposition(unittest.TestCase):

    def test_default_config_template_validates_against_schema(self):
        """Verify that the template generated by macao init strictly complies with schema."""
        parsed = yaml.safe_load(DEFAULT_CONFIG_TEMPLATE)
        is_valid, error = validate_config(parsed)
        self.assertTrue(is_valid, f"Template failed schema validation: {error}")

    def test_config_manager_property_accessors(self):
        """Verify that ConfigManager reads the actual schema-defined paths."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cfg_path = os.path.join(tmpdir, "macao.yaml")
            with open(cfg_path, "w", encoding="utf-8") as f:
                f.write(DEFAULT_CONFIG_TEMPLATE)

            mgr = ConfigManager(cfg_path)
            mgr.load()

            self.assertEqual(mgr.project_name, "macao-demo")
            self.assertEqual(mgr.target_branch, "main")
            self.assertEqual(mgr.remote_name, "origin")
            self.assertEqual(mgr.min_effective_votes, 2)
            self.assertEqual(mgr.max_rework_rounds, 3)
            self.assertTrue(mgr.require_human_signoff)
            self.assertTrue(mgr.auto_rebase_disabled)
            self.assertIsNone(mgr.ci_gate_command)
            self.assertEqual(len(mgr.reviewers_config), 3)

    def test_orchestrator_config_injection(self):
        """Verify Orchestrator receives injected configuration rather than hardcoded fallbacks."""
        custom_config = {
            "max_rework_rounds": 5,
            "min_effective_votes": 3,
            "ci_gate_command": "pytest -q",
            "require_signoff": True
        }
        orch = Orchestrator(project_root=".", config=custom_config)
        self.assertEqual(orch.config["max_rework_rounds"], 5)
        self.assertEqual(orch.config["min_effective_votes"], 3)
        self.assertEqual(orch.config["ci_gate_command"], "pytest -q")
        self.assertTrue(orch.config["require_signoff"])

    def test_adapter_preflight_probes_no_type_error(self):
        """Verify all adapter preflight probes return valid PreflightCheckResult objects."""
        adapters = [
            MockAgentAdapter("mock-1", "mock-cli"),
            ClaudeCodeAdapter(),
            CodexAdapter(),
            OpenCodeAdapter(),
            AntigravityAdapter(),
            KimiAdapter()
        ]
        for adp in adapters:
            res = adp.preflight()
            self.assertIsNotNone(res)
            self.assertIn(adp.cli_name, (res.cli_name, res.agent_id))
            self.assertIsInstance(res.installed, bool)

    def test_adapter_interface_and_log_consistency(self):
        """Verify all real and mock adapters implement capabilities, get_logs, and cancel consistently."""
        adapters = [
            MockAgentAdapter("mock-1", "mock-cli"),
            ClaudeCodeAdapter(),
            CodexAdapter(),
            OpenCodeAdapter(),
            AntigravityAdapter(),
            KimiAdapter()
        ]
        for adp in adapters:
            caps = adp.capabilities()
            self.assertIsNotNone(caps)
            self.assertTrue(caps.can_review or caps.can_execute)

            # Test get_logs without running session returns empty string without TypeError
            logs = adp.get_logs(tail_lines=50)
            self.assertIsInstance(logs, str)
            self.assertEqual(logs, "")

            # Test cancel returns bool
            cancelled = adp.cancel("test")
            self.assertIsInstance(cancelled, bool)

    def test_schemas_dir_lookup_and_env_override(self):
        """Verify get_schemas_dir finds schemas and respects MACAO_SCHEMAS_DIR."""
        from macao.core.schema import get_schemas_dir, SchemaValidator
        d = get_schemas_dir()
        self.assertTrue(d.exists())
        self.assertTrue((d / "vote_result.schema.json").exists())

        # Test SchemaValidator loads schemas successfully
        v = SchemaValidator()
        self.assertIsNotNone(v.get_schema("vote_result"))
        self.assertIsNotNone(v.get_schema("dev_manifest"))
        self.assertIsNotNone(v.get_schema("review_manifest"))

        # Test explicit MACAO_SCHEMAS_DIR override
        with tempfile.TemporaryDirectory() as custom_dir:
            old_env = os.environ.get("MACAO_SCHEMAS_DIR")
            try:
                os.environ["MACAO_SCHEMAS_DIR"] = custom_dir
                custom_path = get_schemas_dir()
                self.assertEqual(custom_path, Path(custom_dir).resolve())
            finally:
                if old_env is not None:
                    os.environ["MACAO_SCHEMAS_DIR"] = old_env
                else:
                    os.environ.pop("MACAO_SCHEMAS_DIR", None)

    def test_parse_duration_units_and_validation(self):
        """Verify parse_duration accurately handles units and raises on invalid format."""
        from macao.workflow.orchestrator import parse_duration
        self.assertEqual(parse_duration("30s"), 30.0)
        self.assertEqual(parse_duration("10m"), 600.0)
        self.assertEqual(parse_duration("2h"), 7200.0)
        self.assertEqual(parse_duration("1d"), 86400.0)
        self.assertEqual(parse_duration(120), 120.0)
        self.assertEqual(parse_duration("", default=300.0), 300.0)
        with self.assertRaises(ValueError):
            parse_duration("invalid_string")

    def test_opencode_agy_cursor_role_and_model_specification_config(self):
        """Verify macao.yaml schema allows model specification on executor and reviewers and flexible roles."""
        from macao.adapter.cursor import CursorAgentAdapter
        custom_yaml = """version: "2.5"
project:
  name: "macao-flexible-roles"
  repository:
    workspace_path: "."
    remote_name: "origin"
    default_branch: "main"
team:
  name: "washdb"
  executor:
    id: "opencode-exec"
    agmsg_member_id: "cc-ds4"
    cli: "opencode"
    adapter: "pty-wrapper"
    model: "GLM 5.3 max"
  reviewers:
    - id: "opencode-rev"
      agmsg_member_id: "qwen"
      cli: "opencode"
      adapter: "pty-wrapper"
      model: "Qwen3.8 max"
      vote_weight: 1
    - id: "cursor-rev"
      agmsg_member_id: "kimi"
      cli: "agent"
      adapter: "pty-wrapper"
      model: "claude-3-7-sonnet"
      vote_weight: 1
    - id: "claude-rev"
      agmsg_member_id: "cc-glm"
      cli: "claude-code"
      adapter: "claude-hook"
      model: "claude-3-5-sonnet"
      vote_weight: 1
policy:
  consensus_rule: "weighted_2/3_v1"
  dictator_cap_enabled: true
  minimum_winning_seats: 2
  seat_quorum_required: 2
  weight_quorum_required: 2
  max_rework_rounds: 3
  review_strategy: "delta_plus_focus"
"""
        parsed = yaml.safe_load(custom_yaml)
        is_valid, error = validate_config(parsed)
        self.assertTrue(is_valid, f"Custom model config failed schema validation: {error}")


    def test_adapter_model_injection_and_role_flexibility(self):
        """Verify all adapters accept model and role configuration in inject_task and capabilities."""
        from macao.adapter.cursor import CursorAgentAdapter
        # 1. OpenCode as Executor with GLM 5.3 max
        opencode_exec = OpenCodeAdapter("opencode-exec", config={"role": "executor", "model": "GLM 5.3 max"})
        self.assertTrue(opencode_exec.capabilities().can_execute)
        self.assertTrue(opencode_exec.capabilities().can_review)

        # 2. OpenCode as Reviewer with Qwen3.8 max
        opencode_rev = OpenCodeAdapter("opencode-rev", config={"role": "reviewer", "model": "Qwen3.8 max"})
        self.assertTrue(opencode_rev.capabilities().can_review)

        # 3. Antigravity as Executor
        agy_exec = AntigravityAdapter("agy-exec", config={"role": "executor", "model": "gemini-2.0-pro"})
        self.assertTrue(agy_exec.capabilities().can_execute)
        self.assertTrue(agy_exec.capabilities().can_review)

        # 4. Cursor Agent as Reviewer
        cursor_adp = CursorAgentAdapter("cursor-rev", config={"role": "reviewer", "model": "claude-3-5-sonnet"})
        self.assertTrue(cursor_adp.capabilities().can_execute)
        self.assertTrue(cursor_adp.capabilities().can_review)

    def test_root_macao_yaml_passes_semantic_validation(self):
        """Verify that the repository's root macao.yaml passes validate_config and ConfigManager.load."""
        root_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "macao.yaml")
        self.assertTrue(os.path.exists(root_path), f"macao.yaml must exist at {root_path}")
        with open(root_path, "r", encoding="utf-8") as f:
            raw_cfg = yaml.safe_load(f)
        is_valid, err = validate_config(raw_cfg)
        self.assertTrue(is_valid, f"Root macao.yaml failed semantic validation: {err}")

        mgr = ConfigManager(root_path)
        loaded = mgr.load()
        self.assertEqual(loaded["project"]["name"], "macao-demo")
        self.assertEqual(mgr.seat_quorum_required, 3)
        self.assertEqual(mgr.weight_quorum_required, 3)


if __name__ == "__main__":
    unittest.main()
